version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-docker
    ports:
      - 8080:80
    volumes:
      - ./srv/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_docker
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:4.0-alpine
    ports:
      - 16380:6379